### ISSUE TITLE
Adjust flow between Login and OAuth processes

### ISSUE THREAD

**Issue by cadecrandall** [googleinterns/step57-2020#24]
_Originally posted by @cxfloeder in https://github.com/googleinterns/step57-2020/pull/22_

**Comment by cadecrandall** [comment]
we need a robust process to check for user authorization prior to sending the oauth request

**Comment by cadecrandall** [comment]
https://github.com/googleinterns/step57-2020/pull/22/files/cdf02a04974fd4318bdf4096d443ef65c4b5bec8#r455254833

**Comment by cxfloeder** [comment]
I have separated the OAuth and login functionality. The front end just needs to use this functionality now. My suggestion would be to call the OAuthConsentServlet directly after a user is logged in. If a user logs out, the InvalidateSessionServlet should be called direclty afterwards.
