### ISSUE TITLE
Create cloudbuild.yaml file to allow PR to be merged on GH.

### ISSUE THREAD

**Issue by cxfloeder** [googleinterns/step57-2020#43]

**Comment by jakecarlson1** [comment]
https://cloud.google.com/cloud-build/docs/building/build-java#using_the_maven_or_gradle_image

**Comment by jakecarlson1** [comment]
https://github.com/googleinterns/step6-2020/blob/97b48f60c5523bdaf15720bd60985d178013c129/cloudbuild.yaml

**Comment by cxfloeder** [comment]
Created and merged a cloudbuild PR
